name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Checks for compile time errors
    - name: Compile
      run: for f in */*.c; do gcc $f -o $f.output -lm; done